apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "coredns-updater.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "coredns-updater.fullname" . }}
  namespace: iguazio-platform
roleRef:
  kind: ClusterRole
  name: {{ include "coredns-updater.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
