apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "coredns-updater.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["nodes", "events"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["ingresses"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["*"]
