apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coredns-updater.fullname" . }}
  labels:
    {{- include "coredns-updater.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "coredns-updater.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "coredns-updater.selectorLabels" . | nindent 8 }}
      name: coredns-update
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "coredns-updater.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag  }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # specify on which node we're running, same code can run on data node as well
        args: ["-n", "app" ]
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 5012
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: coredns-updater
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
